# Generated by Django 5.1 on 2025-03-05 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('box_name', models.CharField(max_length=150, unique=True)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('details', models.TextField()),
                ('shortcode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('CIN_number', models.CharField(max_length=21, unique=True)),
                ('GST_number', models.CharField(max_length=15, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('exhibition_id', models.AutoField(primary_key=True, serialize=False)),
                ('exhibition_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_name', models.CharField(max_length=150, unique=True)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='TTSPL_IMS_App.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaar_card', models.CharField(max_length=12, unique=True)),
                ('pan_card', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_work_location', to='TTSPL_IMS_App.location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('product_size_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_size_breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_size_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacture_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=150)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('purchase_date', models.DateField()),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.category')),
                ('product_images', models.ManyToManyField(related_name='products', to='TTSPL_IMS_App.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='AssignProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('assign_quantity', models.IntegerField(default=0)),
                ('assign_customer_details', models.CharField(max_length=200)),
                ('assign_at', models.DateTimeField(auto_now_add=True)),
                ('assign_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.company')),
                ('assign_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.customer')),
                ('assign_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.employee')),
                ('assign_exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.exhibition')),
                ('assign_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_status', models.CharField(choices=[('ASSIGN', 'assign'), ('RETURN', 'return'), ('SELL', 'sell'), ('DEMO', 'demo'), ('INSPECTION', 'inspection'), ('INSTOCK', 'instock')], default='INSTOCK', max_length=30)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.box')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.product')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.rank')),
            ],
        ),
        migrations.CreateModel(
            name='StockBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_text', models.CharField(max_length=255, unique=True)),
                ('barcode_image', models.ImageField(upload_to='stock_barcodes/')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='TTSPL_IMS_App.stockentry')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=150, unique=True)),
                ('shortcode', models.CharField(max_length=4, unique=True)),
                ('details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='TTSPL_IMS_App.category')),
            ],
        ),
        migrations.AddField(
            model_name='stockentry',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.subcategory'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='TTSPL_IMS_App.company')),
            ],
        ),
        migrations.CreateModel(
            name='TempStockBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_text', models.CharField(max_length=255, unique=True)),
                ('barcode_image', models.ImageField(upload_to='temp_barcodes/')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_barcodes', to='TTSPL_IMS_App.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_barcodes', to='TTSPL_IMS_App.product')),
            ],
        ),
    ]
