# Generated by Django 5.1 on 2025-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproduct',
            name='assign_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
