# Generated by Django 5.1 on 2025-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0002_alter_assignproduct_assign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproduct',
            name='assign_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
