# Generated by Django 5.1 on 2025-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0003_alter_assignproduct_assign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignproduct',
            name='assign_mode',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
