# Generated by Django 5.1 on 2025-03-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0004_assignproduct_assign_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignproduct',
            name='assign_stock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.stockentry'),
        ),
    ]
