# Generated by Django 5.1 on 2025-03-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0005_assignproduct_assign_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignproduct',
            old_name='assign_stock_id',
            new_name='assign_stockentry',
        ),
    ]
