# Generated by Django 5.1 on 2025-03-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0006_rename_assign_stock_id_assignproduct_assign_stockentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignproduct',
            name='assign_stockentry',
        ),
    ]
