# Generated by Django 5.1 on 2025-03-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0007_remove_assignproduct_assign_stockentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignproduct',
            name='stock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.stockentry'),
        ),
    ]
