# Generated by Django 5.1 on 2025-03-11 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0008_assignproduct_stock_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=100, unique=True)),
                ('assign_return_id', models.CharField(max_length=100, unique=True)),
                ('return_mode', models.CharField(max_length=30)),
                ('return_quantity', models.IntegerField(default=0)),
                ('return_customer_details', models.CharField(max_length=200)),
                ('return_at', models.DateTimeField(auto_now_add=True)),
                ('return_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.company')),
                ('return_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.customer')),
                ('return_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.employee')),
                ('return_exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.exhibition')),
                ('return_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.product')),
                ('return_stock_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TTSPL_IMS_App.stockentry')),
            ],
        ),
    ]
