# Generated by Django 5.1 on 2025-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0009_returnproducthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproducthistory',
            name='assign_return_id',
            field=models.CharField(max_length=100),
        ),
    ]
