# Generated by Django 5.1 on 2025-03-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0010_alter_returnproducthistory_assign_return_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducthistory',
            name='return_product_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnproducthistory',
            name='reuturn_assign_at',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
