# Generated by Django 5.1 on 2025-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0011_returnproducthistory_return_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproducthistory',
            name='reuturn_assign_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
