# Generated by Django 5.1 on 2025-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0012_alter_returnproducthistory_reuturn_assign_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproducthistory',
            name='return_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
