# Generated by Django 5.1 on 2025-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0014_alter_returnproducthistory_return_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproducthistory',
            name='return_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
