# Generated by Django 5.1 on 2025-03-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0015_alter_returnproducthistory_return_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducthistory',
            name='reuturn_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
