# Generated by Django 5.1 on 2025-03-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTSPL_IMS_App', '0016_returnproducthistory_reuturn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='product_status',
            field=models.CharField(choices=[('ASSIGN', 'assign'), ('FIXED_ASSET', 'fixed_asset'), ('RETURN', 'return'), ('SELL', 'sell'), ('DEMO', 'demo'), ('INSPECTION', 'inspection'), ('INSTOCK', 'instock')], default='INSTOCK', max_length=30),
        ),
    ]
